
name: AWS Megatests

on:
  pull_request:
    branches:
    - '*'
  push:
     branches:
     - '*'
  release:
    types: [published]

jobs:
  run-awstest:
    name: Run AWS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           python-version: 3.7
       - name: Conda install awscli
         run: conda install -c conda-forge awscli
