
name: AWS Megatests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  install-awscli:
    name: Install awscli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          python-version: 3.7
      - name: Conda install awscli
        run: conda install -c conda-forge awscli 