
name: AWS Megatests

on:
  pull_request:
    branches:
    - '*'
  push:
     branches:
     - '*'
  release:
    types: [published]

jobs:
  run-awstest:
    name: Run AWS test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Install awscli
        run: conda install -c conda-forge awscli
     