
name: AWS Megatests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  install-conda:
    name: Install miniconda
    runs-on: ubuntu-latest
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Conda info
        run: conda install -c conda-forge awscli 
        
