name: nf-core aws test
# This workflow is triggered on pushes and PRs to the repository.
# It runs the `nf-core lint` and markdown lint tests to ensure that the code meets the nf-core guidelines
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
    Awstest:
        runs-on: ${{ matrix.os }}
        matrix:
            os: ['ubuntu-latest']
            python-version: ['3.7']
        steps:
        - uses: goanpeca/setup-miniconda@v1
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Install aws client
          run: conda install -c conda-forge awscli
        - name: Start AWS batch job
          env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_KEY_SECRET}}
          run: |
          aws batch submit-job \
          --job-name nf-core-rnaseq \
          --job-queue 'default-8b3836e0-5eda-11ea-96e5-0a2c3f6a2a32' \
          --job-definition nextflow \
          --container-overrides command=nf-core/rnaseq,\
          "-profile test"
      