name: sarek extra CI
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]  

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [ANNOTATESNPEFF, GERMLINE, SPLITFASTQ, TARGETED, HAPLOTYPECALLER, MANTA, MPILEUP, MUTECT2, STRELKA, TIDDIT]
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        env:
          NXF_VER: '19.04.0'
      - name: Download image
        run: |
          ${GITHUB_WORKSPACE}/scripts/download_image.sh -n docker --source-version dev --target-version dev --test ${{ matrix.test }}
      - name: Run test
        run: |
          ${GITHUB_WORKSPACE}/scripts/run_tests.sh --test ${{ matrix.test }} --verbose