name: sarek extra CI
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]  

jobs:
  minimal:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        genome: [smallerGRCh37, minimalGRCh37]
        intervals: [--no_intervals, '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        env:
          NXF_VER: '19.10.0'
      - name: Download image
        run: |
          docker pull nfcore/sarek:dev
          docker tag nfcore/sarek:dev nfcore/sarek:dev
      - name: Run test
        run: |
          nextflow run . -profile test,docker --skipQC all --verbose --genome ${{ matrix.genome }} ${{ matrix.intervals }} --tools Manta,mpileup,Strelka
  profile:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        profile: [test_splitfastq, test_targeted]
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        env:
          NXF_VER: '19.10.0'
      - name: Download image
        run: |
          docker pull nfcore/sarek:dev
          docker tag nfcore/sarek:dev nfcore/sarek:dev
      - name: Run test
        run: |
          nextflow run . -profile ${{ matrix.profile }},docker --verbose
  tools:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tool: [Haplotypecaller, Freebayes, Manta, mpileup, Mutect2, Strelka]
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        env:
          NXF_VER: '19.10.0'
      - name: Download image
        run: |
          docker pull nfcore/sarek:dev
          docker tag nfcore/sarek:dev nfcore/sarek:dev
      - name: Run test
        run: |
          nextflow run . -profile test_tool,docker --verbose --tools ${{ matrix.tool }}
  annotation:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        annotator: [snpeff]
        specie: [GRCh37]
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        env:
          NXF_VER: '19.10.0'
      - name: Download image
        run: |
          docker pull nfcore/sarek${{ matrix.annotator }}:dev.${{ matrix.specie }}
          docker tag nfcore/sarek${{ matrix.annotator }}:dev.${{ matrix.specie }} nfcore/sarek${{ matrix.annotator }}:dev.${{ matrix.specie }}
      - name: Run test
        run: |
          nextflow run . -profile test_annotation,docker --verbose --tools ${{ matrix.annotator }}